<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="startServiceXSD" targetNamespace="http://legodo.com/startService/" 
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:tns="http://legodo.com/startService/" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.sympany.ch/ApplicationObjects/C4/schemas" schemaLocation="c4_aia_v33.xsd" />
    </schema>
  
  </wsdl:types>
</wsdl:definitions>