micronaut:
    server:
        port: 8080
        # input size limit
        maxRequestSize: 30000000

        netty:
            worker:
                threads: 4

    executors:
        scheduled:
            type: scheduled
            core-pool-size: 3

        io:
            type: fixed
            nThreads: 6

router:
    static:
        resources:
            enabled: true
            mapping: /static/**
            paths: classpath:www

jackson:
    serialization:
        indentOutput: true

