package ch.m1m.soap.hello;

        import ch.m1m.xmlns.soap.hello.*;

        import java.util.logging.Logger;
        import javax.jws.WebMethod;
        import javax.jws.WebParam;
        import javax.jws.WebResult;
        import javax.jws.WebService;
        import javax.jws.soap.SOAPBinding;
        import javax.xml.bind.annotation.XmlSeeAlso;
        import javax.xml.ws.RequestWrapper;
        import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-02-27T20:01:15.087+01:00
 * Generated source version: 3.1.9
 *

@javax.jws.WebService(
        serviceName = "SoapHello",
        portName = "SoapHelloSOAP",
        targetNamespace = "http://xmlns.m1m.ch/soap/hello",
        wsdlLocation = "file:/home/mue/IdeaProjects/soaphello/src/main/resources/SoapHello.wsdl",
        endpointInterface = "ch.m1m.xmlns.soap.hello.SoapHello")
 */

public class SoapHelloSOAP_Impl implements SoapHello {

    private static final Logger LOG = Logger.getLogger(SoapHelloSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see ch.m1m.xmlns.soap.hello.SoapHello#getHello(ch.m1m.xmlns.soap.hello.HelloRequestType parameters)*
     */
    public ch.m1m.xmlns.soap.hello.HelloResponseType getHello(HelloRequestType input) {
        LOG.info("Executing operation getHello" + input);
        try {
            ch.m1m.xmlns.soap.hello.HelloResponseType retInst = new ch.m1m.xmlns.soap.hello.HelloResponseType();
            PersonType person = new PersonType();
            person.setSex("m");
            person.setFirstName("Markus");
            person.setLastName("Mueller");
            retInst.setPerson(person);
            return retInst;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ch.m1m.xmlns.soap.hello.SoapHello#newOperation(java.lang.String in)*
     */
    public java.lang.String newOperation(java.lang.String in) {
        LOG.info("Executing operation newOperation");
        System.out.println(in);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
