
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ch.sympany.it.samples;

import java.util.logging.Logger;

import javax.annotation.Resource;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.xml.ws.WebServiceContext;

import com.legodo.startservice.StartCorrespondenceFault;
import com.legodo.startservice.StartDesignerFault;
import com.legodo.startservice.StartService;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-02-22T11:33:18.010+01:00
 * Generated source version: 3.1.9
 * 
 */

/*
@javax.jws.WebService(
                      serviceName = "startService",
                      portName = "startServiceSOAP",
                      targetNamespace = "http://legodo.com/startService/",
                      wsdlLocation = "file:/Users/mue/work/workspace-soang/starCorrespondenceEndpoint/src/main/resources/legodoStartService.wsdl",
                      endpointInterface = "com.legodo.startservice.StartService")
*/
                      
public class StartServiceSOAP_Impl implements StartService {
  
    @Resource
    WebServiceContext wsContext;

    private static final Logger LOG = Logger.getLogger(StartServiceSOAP_Impl.class.getName());

    /* (non-Javadoc)
     * @see com.legodo.startservice.StartService#startCorrespondence(com.legodo.startservice.Mode mode, com.legodo.startservice.Startup startup, com.legodo.startservice.Settings settings)*
     */
    public java.lang.String startCorrespondence(com.legodo.startservice.Mode mode, com.legodo.startservice.Startup startup, com.legodo.startservice.Settings settings) throws StartCorrespondenceFault   { 
        LOG.info("Executing operation startCorrespondence");
        System.out.println("Executing operation startCorrespondence, mode " + mode);
        System.out.println("  startup=" + startup);
        System.out.println("  settings=" + settings);
        System.out.println("  system prop java.util.logging.manager=" + System.getProperty("java.util.logging.manager"));
        try {
            java.lang.String _return = "not_set_yet";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StartCorrespondenceFault("startCorrespondenceFault...");
    }

    /* (non-Javadoc)
     * @see com.legodo.startservice.StartService#startDesigner(com.legodo.startservice.Mode mode, com.legodo.startservice.Settings settings)*
     */
    public java.lang.String startDesigner(com.legodo.startservice.Mode mode, com.legodo.startservice.Settings settings) throws StartDesignerFault   { 
        LOG.info("Executing operation startDesigner");
        System.out.println("Executing operation startDesigner, mode " + mode);
        System.out.println(settings);
        try {
            java.lang.String _return = "not_set_yet";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StartDesignerFault("startDesignerFault...");
    }

}
